version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-arm7
    main: ./cmd/cli
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X github.com/fopina/speedtest-cli/version.Version={{ .Version }}
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - '7'
  - id: cross
    main: ./cmd/cli
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X github.com/fopina/speedtest-cli/version.Version={{ .Version }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: binary

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers_v2:
  - images:
      - ghcr.io/fopina/{{.ProjectName}}
    tags:
      - '{{ .Version }}'
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "io.artifacthub.package.license": "MIT"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
