version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-arm7
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{ .Version }}
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - '7'
  - id: cross
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}_v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - formats: zip
        goos: windows

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers_v2:
  - images:
      - ghcr.io/fopina/{{.ProjectName}}
    tags:
      - '{{ .Version }}'
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "io.artifacthub.package.license": "MIT"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
