language: go

go:
- 1.12

env:
  global:
    - LDFLAGS="-s -w"

matrix:
  include:
  # gvm update runs after env section
  # so use before_script instead for GO* vars
    - env:
        - BINARY="speedtest-cli_linux_amd64"
        # for alpine!
        - CGO_ENABLED=0
    - before_script:
        - export GOOS=darwin
      env:
        - BINARY=speedtest-cli_darwin_amd64"
    - before_script:
        - export GOOS=windows
      env:
        - BINARY=speedtest-cli_win32.exe
    - before_script:
        - export GOARCH=arm
        - export GOARM=5
      env:
        - BINARY="speedtest-cli_linux_arm"
        - CGO_ENABLED=0

script:
  - go build -o ${BINARY} -ldflags "$LDFLAGS" speedtest.go

before_deploy:
  - if [[ -z $TRAVIS_TAG ]]; then export TRAVIS_TAG="dev-release"; fi

deploy:
  - provider: releases
    api_key: "${GITHUB_TOKEN}"
    file: "${BINARY}"
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: "${GITHUB_TOKEN}"
    file: "${BINARY}"
    skip_cleanup: true
    draft: true
    on:
      tags: false
      branch: dev
