name: 'Go-release'
description: 'Run goreleaser'
inputs:
  flags:
    description: Extra flags for goreleaser
    default: ''
  github-token:
    description: 'Token to login to GHCR and pull image - steps skipped if not provided'
    default: ''
outputs:
  version:
    description: "Released version"
    value: ${{ steps.get_version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: ghcr-login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}


    - name: Run GoReleaser
      id: goreleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: '~> v2'
        args: release --clean ${{ inputs.flags }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Print released version
      id: get_version
      shell: bash
      run: |
        if [ "${{ steps.goreleaser.outputs.metadata }}" ]; then
          VERSION=$(jq -r '.version' <<< '${{ steps.goreleaser.outputs.metadata }}')
          echo "Released version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        else
          echo "No release metadata available"
        fi
